import type { Metadata } from "next";
import { Geist, Geist_Mono, Fustat, Nata_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/core/navbar";
import Footer from "@/components/core/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const fustat = Fustat({
    variable: "--font-fustat",
    subsets: ["latin"],
});

const nataSans = Nata_Sans({
    variable: "--font-nata-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Nefruza",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="pt-br"
            className={`${fustat.variable} ${nataSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
